# Generated by Django 3.2.6 on 2021-08-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
